type tsyn_eStart = (controller:machine, dst:machine);
type tsyn_eShutDown = (controller:machine, dst:machine);
type tsyn_ePongLost = (controller:machine, dst:machine, trial:int);
type tsyn_ePong = (controller:machine, dst:machine, trial:int);
type tsyn_ePing = (controller:machine, dst:machine, fd: machine, trial:int);
type tsyn_eNetworkError = (controller:machine, dst:machine, trial:int);
type tsyn_eNotifyNodesDown = (controller:machine, dst:machine);
event syn_eStart: tsyn_eStart;
event syn_eShutDown: tsyn_eShutDown;
event syn_ePongLost: tsyn_ePongLost;
event syn_ePong: tsyn_ePong;
event syn_ePing: tsyn_ePing;
event syn_eNotifyNodesDown: tsyn_eNotifyNodesDown;
event syn_eNetworkError: tsyn_eNetworkError;
type setting = machine;