type tsyn_eWarmUpReq = (controller:machine, dst:machine);
type tsyn_eWarmUpCompleted = (controller:machine, dst:machine);
type tsyn_eStartEspressoReq = (controller:machine, dst:machine);
type tsyn_eNoWaterError = (controller:machine, dst:machine);
type tsyn_eNoBeansError = (controller:machine, dst:machine);
type tsyn_eGrindBeansReq = (controller:machine, dst:machine);
type tsyn_eGrindBeansCompleted = (controller:machine, dst:machine);
type tsyn_eEspressoCompleted = (controller:machine, dst:machine);
type tsyn_eEspressoButtonPressed = (controller:machine, dst:machine);
type tsyn_eCoffeeMakerReady = (controller:machine, dst:machine);
type tsyn_eCoffeeMakerError = (controller:machine, dst:machine, st:tCoffeeMakerState);
type tsyn_eCoffeeMakerCompleted = (controller:machine, dst:machine);
type tsyn_eCoffeeMachineUser = (controller:machine, dst:machine);
event syn_eWarmUpReq: tsyn_eWarmUpReq;
event syn_eWarmUpCompleted: tsyn_eWarmUpCompleted;
event syn_eStartEspressoReq: tsyn_eStartEspressoReq;
event syn_eNoWaterError: tsyn_eNoWaterError;
event syn_eNoBeansError: tsyn_eNoBeansError;
event syn_eGrindBeansReq: tsyn_eGrindBeansReq;
event syn_eGrindBeansCompleted: tsyn_eGrindBeansCompleted;
event syn_eEspressoCompleted: tsyn_eEspressoCompleted;
event syn_eEspressoButtonPressed: tsyn_eEspressoButtonPressed;
event syn_eCoffeeMakerReady: tsyn_eCoffeeMakerReady;
event syn_eCoffeeMakerError: tsyn_eCoffeeMakerError;
event syn_eCoffeeMakerCompleted: tsyn_eCoffeeMakerCompleted;
event syn_eCoffeeMachineUser: tsyn_eCoffeeMachineUser;
type setting = machine;