// event readReq: (src: machine);
// event getReq: (src: machine);
// type teadRsp = (va: int);
// event readRsp: teadRsp;
// event writeReq : (src: machine, va: int);
// event putReq : (src: machine, va: int);
// event putRsp : (va: int, stat: bool);
// type triteRsp = (va: int, stat: bool);
// event writeRsp : triteRsp;
// event commit;
// event abort;
type tsyn_writeRsp = (controller:machine, dst:machine, va:int, stat:bool);
type tsyn_writeReq = (controller:machine, dst:machine, va:int);
type tsyn_readRsp = (controller:machine, dst:machine, va:int);
type tsyn_readReq = (controller:machine, dst:machine);
type tsyn_putRsp = (controller:machine, dst:machine, va:int, stat:bool);
type tsyn_putReq = (controller:machine, dst:machine, src: machine, va:int);
type tsyn_getReq = (controller:machine, dst:machine);
type tsyn_commit = (controller:machine, dst:machine);
type tsyn_abort = (controller:machine, dst:machine);
event syn_writeRsp: tsyn_writeRsp;
event syn_writeReq: tsyn_writeReq;
event syn_readRsp: tsyn_readRsp;
event syn_readReq: tsyn_readReq;
event syn_putRsp: tsyn_putRsp;
event syn_putReq: tsyn_putReq;
event syn_getReq: tsyn_getReq;
event syn_commit: tsyn_commit;
event syn_abort: tsyn_abort;
type setting = machine;